// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Jg7rcKYirV4ATu_1BGwCRUeiCyB5jwQ',
    appId: '1:921671129284:web:d5e03aee9de409813f9191',
    messagingSenderId: '921671129284',
    projectId: 'student-task-manager-5830c',
    authDomain: 'student-task-manager-5830c.firebaseapp.com',
    storageBucket: 'student-task-manager-5830c.firebasestorage.app',
    measurementId: 'G-CPY3FQN7ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwtW7QUD1wwXTrz0cIvVzh2ypkhy-UqQ',
    appId: '1:921671129284:android:1514234dc0644d7e3f9191',
    messagingSenderId: '921671129284',
    projectId: 'student-task-manager-5830c',
    storageBucket: 'student-task-manager-5830c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0e_gDr2x0urZIxXzU4I36eS8Ec3thSPA',
    appId: '1:921671129284:ios:b69c557db0f079283f9191',
    messagingSenderId: '921671129284',
    projectId: 'student-task-manager-5830c',
    storageBucket: 'student-task-manager-5830c.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0e_gDr2x0urZIxXzU4I36eS8Ec3thSPA',
    appId: '1:921671129284:ios:b69c557db0f079283f9191',
    messagingSenderId: '921671129284',
    projectId: 'student-task-manager-5830c',
    storageBucket: 'student-task-manager-5830c.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagerProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Jg7rcKYirV4ATu_1BGwCRUeiCyB5jwQ',
    appId: '1:921671129284:web:85148c564e8d88a33f9191',
    messagingSenderId: '921671129284',
    projectId: 'student-task-manager-5830c',
    authDomain: 'student-task-manager-5830c.firebaseapp.com',
    storageBucket: 'student-task-manager-5830c.firebasestorage.app',
    measurementId: 'G-KH1NRDDKE6',
  );

}